-- 코드를 입력하세요
SELECT gb.TITLE, gb.BOARD_ID, gr.REPLY_ID, gr.WRITER_ID, gr.CONTENTS, DATE_FORMAT(gr.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS gr
LEFT JOIN USED_GOODS_BOARD AS gb
ON gb.BOARD_ID = gr.BOARD_ID
WHERE DATE_FORMAT(gb.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY gr.CREATED_DATE, gb.TITLE